Algoritmo "semnome"
// Disciplina   : [UC4 - Lógica de Programação]
// Professor   : Richard Brosler 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/05/2022
Var
// Seção de Declarações das variáveis 
contagem:inteiro

Inicio
 contagem <- 0
  enquanto (contagem <= 10) faca
   escreval ("5x ",contagem,"=",5*contagem)
    contagem <- contagem + 1
   fimenquanto
Fimalgoritmo