Algoritmo "semnome"
// Disciplina   : [UC4 - Lógica de Programação]
// Professor   : Richard Brosler 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 14/05/2022
Var
 Numero:inteiro


Inicio
 Escreval("Digite um número")
  Leia(Numero)
  se Numero%2 = 0 entao
 Escreval ("O número digitado é par")
 fimse
  se Numero%2 <> 0 entao
 Escreval ("O número digitado é impar")
 fimse


Fimalgoritmo