Algoritmo "Real_DOLAR"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/05/2022
Var
moedaDolar: real
moedaReal: real
Inicio
escreva("Real:")
Leia (moedaReal)
moedaDolar<- moedaReal / 3.25
escreval("Dolar:", moedaDolar)
Fimalgoritmo