Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/05/2022
Var
  Valor:inteiro
  Unidade:inteiro
Inicio
escreval("Digite um valor de até 3 dígitos")
Leia(Valor)
Unidade <- Valor mod 10
escreval ("O resultado é:", Unidade)

Fimalgoritmo